//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор_подряда
    {
        public System.DateTime ДатаДог { get; set; }
        public int КодСтавки { get; set; }
        public int Код_коэффициента { get; set; }
        public int НомерДог { get; set; }
        public int Шифр { get; set; }
    
        public virtual Объект Объект { get; set; }
        public virtual Объект Объект1 { get; set; }
    }
}
