//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнитель
    {
        public int КодИсполнителя { get; set; }
        public int КодЗаказчик { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
    
        public virtual Заказчик Заказчик { get; set; }
        public virtual Заказчик Заказчик1 { get; set; }
    }
}
