//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнитель
    {
        public int КодИсполнителя { get; set; }
        public int КодЗаказчик { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
    
        public virtual Заказчик Заказчик { get; set; }
        public virtual Заказчик Заказчик1 { get; set; }
    }
}
