//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Локальная_смета
    {
        public int КодВидаРабот { get; set; }
        public int Шифр { get; set; }
        public int КодРаботы { get; set; }
        public int КодСтавки { get; set; }
        public int Код_коэффициента { get; set; }
        public Nullable<double> ФизОбъемРабот { get; set; }
        public Nullable<double> СтоимостьРаботы { get; set; }
        public Nullable<double> ТрудоемкостьРаботы { get; set; }
    
        public virtual Справочник_расценок Справочник_расценок { get; set; }
        public virtual Объект Объект { get; set; }
        public virtual Справочник_расценок Справочник_расценок1 { get; set; }
        public virtual Объект Объект1 { get; set; }
    }
}
