//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Локальная_смета
    {
        public int КодВидаРабот { get; set; }
        public int Шифр { get; set; }
        public int КодРаботы { get; set; }
        public int КодСтавки { get; set; }
        public int Код_коэффициента { get; set; }
        public Nullable<double> ФизОбъемРабот { get; set; }
        public Nullable<double> СтоимостьРаботы { get; set; }
        public Nullable<double> ТрудоемкостьРаботы { get; set; }
    
        public virtual Справочник_расценок Справочник_расценок { get; set; }
        public virtual Объект Объект { get; set; }
        public virtual Справочник_расценок Справочник_расценок1 { get; set; }
        public virtual Объект Объект1 { get; set; }
    }
}
