//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проектная_организация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проектная_организация()
        {
            this.Объект = new HashSet<Объект>();
            this.Объект1 = new HashSet<Объект>();
        }
    
        public string УНП { get; set; }
        public int КодПроектировщика { get; set; }
        public string ЮрАдрес { get; set; }
        public string Р_с { get; set; }
        public string Тел { get; set; }
        public string ЭлПочта { get; set; }
        public string НаименованиеПроектиров { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объект> Объект { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объект> Объект1 { get; set; }
    }
}
