//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_видов_работ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Справочник_видов_работ()
        {
            this.Справочник_расценок = new HashSet<Справочник_расценок>();
            this.Справочник_расценок1 = new HashSet<Справочник_расценок>();
        }
    
        public string ЕдИзмОб { get; set; }
        public int КодВидаРабот { get; set; }
        public string ЕдИзмТруд { get; set; }
        public string ВидРабот { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Справочник_расценок> Справочник_расценок { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Справочник_расценок> Справочник_расценок1 { get; set; }
    }
}
