//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeta_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_расценок
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Справочник_расценок()
        {
            this.Локальная_смета = new HashSet<Локальная_смета>();
            this.Локальная_смета1 = new HashSet<Локальная_смета>();
        }
    
        public int КодРаботы { get; set; }
        public int КодВидаРабот { get; set; }
        public double ЗатратыТрудаЕдОбъема { get; set; }
        public string ИмяРаботы { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Локальная_смета> Локальная_смета { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Локальная_смета> Локальная_смета1 { get; set; }
        public virtual Справочник_видов_работ Справочник_видов_работ { get; set; }
        public virtual Справочник_видов_работ Справочник_видов_работ1 { get; set; }
    }
}
